// Generated by scripts/generate-purchase-schemas.py.
import Foundation

internal enum PurchaseSchemas {
    static let result = AnsightToolSchema(json: .object([
        "type": .string("object"),
        "properties": .object([
            "schema": .object([
                "type": .string("string"),
                "enum": .array([.string("ansight.purchases.v1")])
            ]),
            "capturedAt": .object([
                "type": .string("integer")
            ]),
            "droppedEvents": .object([
                "type": .string("integer")
            ]),
            "coverage": .object([
                "type": .string("string"),
                "enum": .array([.string("observedOnly")])
            ]),
            "observations": .object([
                "type": .string("array"),
                "items": .object([
                    "type": .string("object"),
                    "properties": .object([
                        "productId": .object([
                            "type": .string("string")
                        ]),
                        "source": .object([
                            "type": .string("string")
                        ]),
                        "state": .object([
                            "type": .string("string")
                        ]),
                        "verification": .object([
                            "type": .string("string")
                        ]),
                        "environment": .object([
                            "type": .string("string")
                        ]),
                        "productType": .object([
                            "type": .string("string")
                        ]),
                        "transactionRef": .object([
                            "type": .array([.string("string"), .string("null")])
                        ]),
                        "observedAt": .object([
                            "type": .string("integer")
                        ]),
                        "entitled": .object([
                            "type": .array([.string("boolean"), .string("null")])
                        ]),
                        "finished": .object([
                            "type": .array([.string("boolean"), .string("null")])
                        ]),
                        "acknowledged": .object([
                            "type": .array([.string("boolean"), .string("null")])
                        ]),
                        "consumed": .object([
                            "type": .array([.string("boolean"), .string("null")])
                        ]),
                        "deliveryCount": .object([
                            "type": .array([.string("integer"), .string("null")])
                        ]),
                        "expiresAt": .object([
                            "type": .array([.string("integer"), .string("null")])
                        ]),
                        "gracePeriodExpiresAt": .object([
                            "type": .array([.string("integer"), .string("null")])
                        ])
                    ]),
                    "required": .array([.string("productId"), .string("source"), .string("observedAt"), .string("state"), .string("verification"), .string("environment"), .string("productType")]),
                    "additionalProperties": .bool(false)
                ])
            ]),
            "products": .object([
                "type": .string("array"),
                "items": .object([
                    "type": .string("object"),
                    "properties": .object([
                        "productId": .object([
                            "type": .string("string")
                        ]),
                        "available": .object([
                            "type": .string("boolean")
                        ]),
                        "observedAt": .object([
                            "type": .string("integer")
                        ]),
                        "productType": .object([
                            "type": .string("string")
                        ]),
                        "displayPrice": .object([
                            "type": .array([.string("string"), .string("null")])
                        ]),
                        "price": .object([
                            "type": .array([.string("string"), .string("null")])
                        ]),
                        "currencyCode": .object([
                            "type": .array([.string("string"), .string("null")])
                        ])
                    ]),
                    "required": .array([.string("productId"), .string("available"), .string("observedAt"), .string("productType")]),
                    "additionalProperties": .bool(false)
                ])
            ]),
            "status": .object([
                "type": .string("string"),
                "enum": .array([.string("pass"), .string("fail"), .string("inconclusive")])
            ]),
            "checks": .object([
                "type": .string("array"),
                "items": .object([
                    "type": .string("object"),
                    "properties": .object([
                        "source": .object([
                            "type": .string("string")
                        ]),
                        "status": .object([
                            "type": .string("string"),
                            "enum": .array([.string("pass"), .string("fail"), .string("inconclusive")])
                        ]),
                        "reason": .object([
                            "type": .string("string")
                        ])
                    ]),
                    "required": .array([.string("source"), .string("status"), .string("reason")]),
                    "additionalProperties": .bool(false)
                ])
            ]),
            "nextCursor": .object([
                "type": .string("integer")
            ]),
            "cursorGap": .object([
                "type": .string("boolean")
            ])
        ]),
        "required": .array([.string("schema"), .string("capturedAt"), .string("droppedEvents"), .string("coverage"), .string("observations"), .string("products")]),
        "additionalProperties": .bool(false)
    ]))
}
