// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum AnsightMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class AnsightMessagesPigeonCodecReader: FlutterStandardReader {
}

private class AnsightMessagesPigeonCodecWriter: FlutterStandardWriter {
}

private class AnsightMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AnsightMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AnsightMessagesPigeonCodecWriter(data: data)
  }
}

class AnsightMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AnsightMessagesPigeonCodec(readerWriter: AnsightMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AnsightNativeHostApi {
  func invoke(method: String, argumentsJson: String?, completion: @escaping (Result<String, Error>) -> Void)
  func queueBinaryTransfer(requestId: String, data: FlutterStandardTypedData, chunkBytes: Int64, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AnsightNativeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AnsightMessagesPigeonCodec.shared }
  /// Sets up an instance of `AnsightNativeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AnsightNativeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let invokeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ansight_flutter.AnsightNativeHostApi.invoke\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invokeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let methodArg = args[0] as! String
        let argumentsJsonArg: String? = nilOrValue(args[1])
        api.invoke(method: methodArg, argumentsJson: argumentsJsonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      invokeChannel.setMessageHandler(nil)
    }
    let queueBinaryTransferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ansight_flutter.AnsightNativeHostApi.queueBinaryTransfer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queueBinaryTransferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let dataArg = args[1] as! FlutterStandardTypedData
        let chunkBytesArg = args[2] as! Int64
        api.queueBinaryTransfer(requestId: requestIdArg, data: dataArg, chunkBytes: chunkBytesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queueBinaryTransferChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AnsightDartApiProtocol {
  func onNativeEvent(name nameArg: String, payloadJson payloadJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onToolCall(requestJson requestJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AnsightDartApi: AnsightDartApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: AnsightMessagesPigeonCodec {
    return AnsightMessagesPigeonCodec.shared
  }
  func onNativeEvent(name nameArg: String, payloadJson payloadJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ansight_flutter.AnsightDartApi.onNativeEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([nameArg, payloadJsonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onToolCall(requestJson requestJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ansight_flutter.AnsightDartApi.onToolCall\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestJsonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
