// Generated by scripts/generate-purchase-schemas.py.
namespace Ansight.Purchases;

using Ansight.Tools;

internal static class PurchaseSchemas
{
    internal static ToolSchema Result { get; } = ToolSchema.Object(properties: new Dictionary<string, ToolSchema> {
        ["schema"] = ToolSchema.String(enumValues: ["ansight.purchases.v1"]),
        ["capturedAt"] = ToolSchema.Integer(),
        ["droppedEvents"] = ToolSchema.Integer(),
        ["coverage"] = ToolSchema.String(enumValues: ["observedOnly"]),
        ["observations"] = ToolSchema.Array(ToolSchema.Object(properties: new Dictionary<string, ToolSchema> {
                ["productId"] = ToolSchema.String(),
                ["source"] = ToolSchema.String(),
                ["state"] = ToolSchema.String(),
                ["verification"] = ToolSchema.String(),
                ["environment"] = ToolSchema.String(),
                ["productType"] = ToolSchema.String(),
                ["transactionRef"] = ToolSchema.String(nullable: true),
                ["observedAt"] = ToolSchema.Integer(),
                ["entitled"] = ToolSchema.Boolean(nullable: true),
                ["finished"] = ToolSchema.Boolean(nullable: true),
                ["acknowledged"] = ToolSchema.Boolean(nullable: true),
                ["consumed"] = ToolSchema.Boolean(nullable: true),
                ["deliveryCount"] = ToolSchema.Integer(nullable: true),
                ["expiresAt"] = ToolSchema.Integer(nullable: true),
                ["gracePeriodExpiresAt"] = ToolSchema.Integer(nullable: true)
            }, required: ["productId", "source", "observedAt", "state", "verification", "environment", "productType"])),
        ["products"] = ToolSchema.Array(ToolSchema.Object(properties: new Dictionary<string, ToolSchema> {
                ["productId"] = ToolSchema.String(),
                ["available"] = ToolSchema.Boolean(),
                ["observedAt"] = ToolSchema.Integer(),
                ["productType"] = ToolSchema.String(),
                ["displayPrice"] = ToolSchema.String(nullable: true),
                ["price"] = ToolSchema.String(nullable: true),
                ["currencyCode"] = ToolSchema.String(nullable: true)
            }, required: ["productId", "available", "observedAt", "productType"])),
        ["status"] = ToolSchema.String(enumValues: ["pass", "fail", "inconclusive"]),
        ["checks"] = ToolSchema.Array(ToolSchema.Object(properties: new Dictionary<string, ToolSchema> {
                ["source"] = ToolSchema.String(),
                ["status"] = ToolSchema.String(enumValues: ["pass", "fail", "inconclusive"]),
                ["reason"] = ToolSchema.String()
            }, required: ["source", "status", "reason"])),
        ["nextCursor"] = ToolSchema.Integer(),
        ["cursorGap"] = ToolSchema.Boolean()
    }, required: ["schema", "capturedAt", "droppedEvents", "coverage", "observations", "products"]);
}
