<Project>

  <PropertyGroup>
    <AnsightPackageVersion>1.0.2-preview.4</AnsightPackageVersion>
    <AnsightPackageProjectUrl>https://www.ansight.ai</AnsightPackageProjectUrl>
    <AnsightRepositoryUrl>https://github.com/ansight-ai/ansight-sdk</AnsightRepositoryUrl>
    <ShouldUnsetParentConfigurationAndPlatform Condition="'$(ShouldUnsetParentConfigurationAndPlatform)' == '' and '$(BuildingSolutionFile)' == 'true'">false</ShouldUnsetParentConfigurationAndPlatform>
  </PropertyGroup>

  <PropertyGroup>
    <PackageVersion Condition="'$(PackageVersion)' == ''">$(AnsightPackageVersion)</PackageVersion>
    <Version Condition="'$(Version)' == ''">$(PackageVersion)</Version>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(PackageVersion)</InformationalVersion>
    <Authors Condition="'$(Authors)' == ''">Ansight AI</Authors>
    <Company Condition="'$(Company)' == ''">Ansight AI</Company>
    <Product Condition="'$(Product)' == ''">Ansight</Product>
    <PackageProjectUrl Condition="'$(PackageProjectUrl)' == ''">$(AnsightPackageProjectUrl)</PackageProjectUrl>
    <RepositoryUrl Condition="'$(RepositoryUrl)' == ''">$(AnsightRepositoryUrl)</RepositoryUrl>
    <RepositoryType Condition="'$(RepositoryType)' == ''">git</RepositoryType>
    <PackageLicenseFile Condition="'$(PackageLicenseFile)' == ''">LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance Condition="'$(PackageRequireLicenseAcceptance)' == ''">true</PackageRequireLicenseAcceptance>
    <PackageReadmeFile Condition="'$(PackageReadmeFile)' == ''">README.md</PackageReadmeFile>
    <PackageIcon Condition="'$(PackageIcon)' == ''">icon.png</PackageIcon>
    <PackageOutputPath Condition="'$(PackageOutputPath)' == ''">$(MSBuildThisFileDirectory)products</PackageOutputPath>
  </PropertyGroup>

</Project>
