<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Ansight.Tools.SecureStorage</AssemblyName>
    <RootNamespace>Ansight.Tools.SecureStorage</RootNamespace>

    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Ansight.Tools.SecureStorage</PackageId>
    <Description>Encrypted storage, Keychain, and Keystore remote tools for the Ansight .NET SDK.</Description>
    <PackageTags>ansight;tools;securestorage;keychain;keystore;encryptedstorage</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ansight\Ansight.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
    <PackageReference Include="Xamarin.AndroidX.Security.SecurityCrypto" Version="1.1.0.4-alpha07" />
  </ItemGroup>

</Project>
