# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  ansight_ios_path = '../../../ios'
  pod 'AnsightCore', :path => ansight_ios_path
  pod 'AnsightPairingQR', :path => ansight_ios_path
  pod 'AnsightToolsDatabase', :path => ansight_ios_path
  pod 'AnsightToolsFileDescriptorDiagnostics', :path => ansight_ios_path
  pod 'AnsightToolsFileSystem', :path => ansight_ios_path
  pod 'AnsightToolsPreferences', :path => ansight_ios_path
  pod 'AnsightToolsReflection', :path => ansight_ios_path
  pod 'AnsightToolsSecureStorage', :path => ansight_ios_path
  pod 'AnsightToolsVisualTree', :path => ansight_ios_path
  pod 'Ansight', :path => ansight_ios_path
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
