#!/usr/bin/env python3
"""Generate base-SDK tool result schemas from the shared purchase wire contract."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
schema = json.loads((ROOT / 'docs/contracts/purchases/result.schema.json').read_text())


def emit(value, language, depth=0):
    nullable = isinstance(value['type'], list)
    kind = value['type'][0] if nullable else value['type']
    if language == 'swift':
        def swift(v, indent=1):
            if isinstance(v, dict):
                return '.object([\n' + ',\n'.join('    ' * (indent + 1) + json.dumps(k) + ': ' + swift(x, indent + 1) for k, x in v.items()) + '\n' + '    ' * indent + '])'
            if isinstance(v, list):
                return '.array([' + ', '.join(swift(x) for x in v) + '])'
            if isinstance(v, bool):
                return '.bool(' + str(v).lower() + ')'
            return '.string(' + json.dumps(v) + ')'
        return 'AnsightToolSchema(json: ' + swift(value) + ')'
    if kind == 'object':
        if language == 'csharp':
            fields = ',\n'.join('    ' * (depth + 2) + '[' + json.dumps(k) + '] = ' + emit(v, language, depth+1) for k,v in value['properties'].items())
            return 'ToolSchema.Object(properties: new Dictionary<string, ToolSchema> {\n' + fields + '\n' + '    '*(depth+1) + '}, required: [' + ', '.join(map(json.dumps,value['required'])) + '])'
        fields = ',\n'.join('    ' * (depth + 2) + json.dumps(k) + ' to ' + emit(v, language, depth+1) for k,v in value['properties'].items())
        return 'ToolSchema.obj(properties = mapOf(\n' + fields + '\n' + '    '*(depth+1) + '), required = listOf(' + ', '.join(map(json.dumps,value['required'])) + '))'
    if kind == 'array':
        return ('ToolSchema.Array(' if language == 'csharp' else 'ToolSchema.array(') + emit(value['items'],language,depth+1) + ')'
    names = {'string':'String','integer':'Integer','boolean':'Boolean'} if language == 'csharp' else {'string':'string','integer':'integer','boolean':'bool'}
    args = []
    if nullable: args.append('nullable: true' if language == 'csharp' else 'nullable = true')
    if 'enum' in value:
        args.append(('enumValues: [' if language == 'csharp' else 'enumValues = listOf(') + ', '.join(map(json.dumps,value['enum'])) + (']' if language == 'csharp' else ')'))
    return 'ToolSchema.' + names[kind] + '(' + ', '.join(args) + ')'

outputs = {
    'src/dotnet/Ansight.Core/Purchases/PurchaseSchemas.cs': '// Generated by scripts/generate-purchase-schemas.py.\nnamespace Ansight.Purchases;\n\nusing Ansight.Tools;\n\ninternal static class PurchaseSchemas\n{\n    internal static ToolSchema Result { get; } = ' + emit(schema,'csharp') + ';\n}\n',
    'src/android/ansight-core/src/main/kotlin/ai/ansight/runtime/purchases/PurchaseSchemas.kt': '// Generated by scripts/generate-purchase-schemas.py.\npackage ai.ansight.runtime.purchases\n\nimport ai.ansight.runtime.ToolSchema\n\ninternal object PurchaseSchemas {\n    val result = ' + emit(schema,'kotlin') + '\n}\n',
    'src/ios/Sources/AnsightCore/Purchases/PurchaseSchemas.swift': '// Generated by scripts/generate-purchase-schemas.py.\nimport Foundation\n\ninternal enum PurchaseSchemas {\n    static let result = ' + emit(schema,'swift') + '\n}\n',
}
for path, content in outputs.items():
    (ROOT/path).write_text(content)
