org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
ansightAndroidGroup=ai.ansight
ansightAndroidArtifactId=ansight-android
ansightAndroidCoreArtifactId=ansight-core-android
ansightAndroidPairingArtifactId=ansight-pairing-android
ansightAndroidVisualTreeArtifactId=ansight-tools-visualtree-android
ansightAndroidFileSystemArtifactId=ansight-tools-filesystem-android
ansightAndroidFileDescriptorDiagnosticsArtifactId=ansight-tools-filedescriptordiagnostics-android
ansightAndroidPreferencesArtifactId=ansight-tools-preferences-android
ansightAndroidSecureStorageArtifactId=ansight-tools-securestorage-android
ansightAndroidDatabaseArtifactId=ansight-tools-database-android
ansightAndroidReflectionArtifactId=ansight-tools-reflection-android
ansightAndroidVersion=1.0.2-preview.6
