<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Ansight.Tools.Preferences</AssemblyName>
    <RootNamespace>Ansight.Tools.Preferences</RootNamespace>

    <IsPackable>true</IsPackable>
    <PackageId>Ansight.Tools.Preferences</PackageId>
    <Description>Shared preferences and user defaults remote tools for the Ansight .NET SDK.</Description>
    <PackageTags>ansight;tools;preferences;sharedpreferences;nsuserdefaults;storage</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ansight\Ansight.csproj" />
  </ItemGroup>

</Project>
