<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ansight.Core\Ansight.Core.csproj" />
    <ProjectReference Include="..\..\Ansight.Annotations\Ansight.Annotations.csproj" />
    <ProjectReference Include="..\..\Ansight.OfflineCapture\Ansight.OfflineCapture.csproj" />
    <ProjectReference Include="..\..\Ansight.Profiling.DotNet\Ansight.Profiling.DotNet.csproj" />
    <ProjectReference Include="..\..\Ansight\Ansight.csproj" />
    <ProjectReference Include="..\..\Ansight.Maui\Ansight.Maui.csproj" />
    <ProjectReference Include="..\..\Ansight.Tools.Database\Ansight.Tools.Database.csproj" />
    <ProjectReference Include="..\..\Ansight.Tools.FileSystem\Ansight.Tools.FileSystem.csproj" />
    <ProjectReference Include="..\..\Ansight.Tools.Maui\Ansight.Tools.Maui.csproj" />
    <ProjectReference Include="..\..\Ansight.Tools.Preferences\Ansight.Tools.Preferences.csproj" />
    <ProjectReference Include="..\..\Ansight.Tools.Reflection\Ansight.Tools.Reflection.csproj" />
    <ProjectReference Include="..\..\Ansight.Tools.SecureStorage\Ansight.Tools.SecureStorage.csproj" />
    <ProjectReference Include="..\..\Ansight.Tools.VisualTree\Ansight.Tools.VisualTree.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\bundled-profile.txt" LogicalName="ansight.json" />
  </ItemGroup>

</Project>
