// Generated by scripts/generate-purchase-schemas.py.
package ai.ansight.runtime.purchases

import ai.ansight.runtime.ToolSchema

internal object PurchaseSchemas {
    val result = ToolSchema.obj(properties = mapOf(
        "schema" to ToolSchema.string(enumValues = listOf("ansight.purchases.v1")),
        "capturedAt" to ToolSchema.integer(),
        "droppedEvents" to ToolSchema.integer(),
        "coverage" to ToolSchema.string(enumValues = listOf("observedOnly")),
        "observations" to ToolSchema.array(ToolSchema.obj(properties = mapOf(
                "productId" to ToolSchema.string(),
                "source" to ToolSchema.string(),
                "state" to ToolSchema.string(),
                "verification" to ToolSchema.string(),
                "environment" to ToolSchema.string(),
                "productType" to ToolSchema.string(),
                "transactionRef" to ToolSchema.string(nullable = true),
                "observedAt" to ToolSchema.integer(),
                "entitled" to ToolSchema.bool(nullable = true),
                "finished" to ToolSchema.bool(nullable = true),
                "acknowledged" to ToolSchema.bool(nullable = true),
                "consumed" to ToolSchema.bool(nullable = true),
                "deliveryCount" to ToolSchema.integer(nullable = true),
                "expiresAt" to ToolSchema.integer(nullable = true),
                "gracePeriodExpiresAt" to ToolSchema.integer(nullable = true)
            ), required = listOf("productId", "source", "observedAt", "state", "verification", "environment", "productType"))),
        "products" to ToolSchema.array(ToolSchema.obj(properties = mapOf(
                "productId" to ToolSchema.string(),
                "available" to ToolSchema.bool(),
                "observedAt" to ToolSchema.integer(),
                "productType" to ToolSchema.string(),
                "displayPrice" to ToolSchema.string(nullable = true),
                "price" to ToolSchema.string(nullable = true),
                "currencyCode" to ToolSchema.string(nullable = true)
            ), required = listOf("productId", "available", "observedAt", "productType"))),
        "status" to ToolSchema.string(enumValues = listOf("pass", "fail", "inconclusive")),
        "checks" to ToolSchema.array(ToolSchema.obj(properties = mapOf(
                "source" to ToolSchema.string(),
                "status" to ToolSchema.string(enumValues = listOf("pass", "fail", "inconclusive")),
                "reason" to ToolSchema.string()
            ), required = listOf("source", "status", "reason"))),
        "nextCursor" to ToolSchema.integer(),
        "cursorGap" to ToolSchema.bool()
    ), required = listOf("schema", "capturedAt", "droppedEvents", "coverage", "observations", "products"))
}
